---
title: "Simulation_Results_Once"
author: "Z. D Kuang"
date: "`r Sys.Date()`"
output: html_document
---

```{r, packages loading and default set,echo = FALSE, message = FALSE, warning = FALSE}
library(glmnet)
library(lassoshooting)
library(mvtnorm)
library(pROC)
library(rmutil)
library(grplasso)
library(Matrix)
library(sim1000G)
library(ggplot2)
library(dplyr)
library(tidyr)
source('COMMUTE_sim_example.R')
source('core_functions_v4_woodbury.R')
source('fastCOMMUTE_functions.R')
```



```{r Overall SETTING}
id <- 1# set 1 first to try. id <- as.numeric(Sys.getenv("SLURM_ARRAY_TASK_ID"))
sim_setting <- expand.grid(sim = 1:100, delta = 0.8, h = c("(10,10;10)","(30,30;30)","(60,60;60)","(10,60;60)"), r = 25)

sim = sim_setting[id, 'sim']
sig.delta = sim_setting[id, 'delta'] 
# h.tmp = sim_setting[id, 'h'] 
# h = c(as.numeric(gsub(".*\\((.*)\\,.*", "\\1", h.tmp)), as.numeric(gsub(".*\\,(.*)\\;.*", "\\1", h.tmp)), as.numeric(gsub(".*\\;(.*)\\).*", "\\1", h.tmp)))

r = sim_setting[id, 'r']
dir_out = 'path_to_save_result'

exact = FALSE             #TRUE=S1; FALSE=S2
K = 3                     #total number of source population 
p = 80                  #number of variables
diffperct = 0.1
h= rep(p*diffperct,3)   #Difference between target and source
s = p/2
n0 = 100                  #target population size
nt = c(2000, 2500, 3000)    #source population size
n.test = 1000
intercept = rep(1, K+1)
LOOP=1
 # import data
 X.pool = data.matrix(read.table('./Xpool.txt', header = F))
```

### beta.true1 & fastCOMMUTE

Note: Beta.true1 is generated by the formula $(X^{T}X)^{-1}X^{T}Y$. We don't use this for the final result. It's only for the reference. We only used Beta.true2(Lasso).

M0-M3, p, and rate of difference are followed in the simulation result table.

```{r Generate fastCOMMUTE DONT NEED TO DO IT AGAIN}
source('core_functions_v4_woodbury.R')
source('fastCOMMUTE_functions.R')
diffloop<-c(2,4)
 ploop<-c(60,100)
 mselist<-matrix(0,LOOP,K+1+1+1+1)
for (k in diffloop) {
  for (j in ploop) {
 diffperct = k*0.01
 p = j
 s = p/2
 h= rep(p*diffperct,3)   #Difference between target and source
 


 # Only Target & M=0 to M=K
 mseout = matrix(0,LOOP,K+1+1+1+1)

# Simulation results  
for (loop in 1:LOOP) {
#set.seed(sim = loop)
 DATA<-data_generation(loop, p, s, K, n0, nt, nov = "large", h, sig.delta, intercept, exact, r, n.test)
 X.tar =DATA$X.tar
 X.src =DATA$X.src
 y.tar =DATA$y.tar
 y.src =DATA$y.src
 delta.TL =DATA$delta.TL
 wthreshold = DATA$wthreshold 
 beta.true = DATA$beta.true
 beta.tar = ginv(t(X.tar)%*%X.tar)%*%t(X.tar)%*%y.tar

 
 a<-beta_fastCOMMUTE_generation(K, method = "fastcommute",nov = "small",X.tar,X.src,y.tar,y.src,delta.TL,wthreshold,beta.true)
   
 
# Only Target
 mseout[loop,1] =mse.fun(beta.true, beta.tar)
# M=0 
 mseout[loop,2] = mse.fun(beta.true, a[[K+1]])
# M=1 to M=K 
 for(i in 1:K){
 mseout[loop,i+2] = mse.fun(beta.true, a[[i]])
    
 }
 # lable p and diff
 mseout[loop,6] = p
 mseout[loop,7] = diffperct
}
  
  mselist<-rbind(mselist,mseout)
  
  }
} 
 
# save(mselist,file = "boxplot121.RData") 
```


# COMMUTE

```{r}
source('COMMUTE_sim_example.R')
mselistCOMMUTE<-matrix(0,LOOP*7 ,4)
for (k in diffloop) {
  for (j in ploop) {
 diffperct = k*0.01
 p = j
 s = p/2
 h= rep(p*diffperct,3)   #Difference between target and source
 # if(j==500){
 #    h= c(10,20,20)   #Difference between target and source
 # }
 # if(j==1000){
 #    h= c(20,40,40)   #Difference between target and source
 # }

# Simulation results  
for (loop in 1:LOOP) {
 COMMUTEout = tryCatch(simu(loop, p, s, K, n0, nt, h, sig.delta, intercept, exact=FALSE, r, n.test), error=function(err) list(matrix(NA,7,4)))
 mselistCOMMUTE<-rbind(mselistCOMMUTE,as.matrix(COMMUTEout))
 
                     }
 
                    }
                   }      


```


# Generating Results(only LassoTarget) 

Beta.true2(Lasso)

```{r}
mselistLASSOTargetOnly<-matrix(0,LOOP,4)
for (k in diffloop) {
  for (j in ploop) {
 diffperct = k*0.01
 p = j
 s = p/2
 h= rep(p*diffperct,3)   #Difference between target and source


# Simulation results  
for (loop in 1:LOOP) {
#set.seed(sim = loop)
  
 COMMUTEout = tryCatch(simutaronly(loop, p, s, K, n0, nt, h, sig.delta, intercept, exact, r, n.test), error=function(err) list(matrix(NA,1,4)))
 mselistLASSOTargetOnly<-rbind(mselistLASSOTargetOnly,as.matrix(COMMUTEout))
 
}
 
  
  
  }
} 
 
```
