---
title: "Boxplots"
author: "Zhuodiao Kuang"
date: "`r Sys.Date()`"
output: html_document
---


```{r, packages loading and default set,echo = FALSE, message = FALSE, warning = FALSE}
library(glmnet)
library(lassoshooting)
library(mvtnorm)
library(pROC)
library(rmutil)
library(grplasso)
library(Matrix)
library(sim1000G)
library(ggplot2)
library(dplyr)
library(tidyr)
source('fastCOMMUTE_functions.R')

```



```{r GENERAL SETTING}
id <- 1# set 1 first to try. id <- as.numeric(Sys.getenv("SLURM_ARRAY_TASK_ID"))
sim_setting <- expand.grid(sim = 1:100, delta = 0.8, h = c("(10,10;10)","(30,30;30)","(60,60;60)","(10,60;60)"), r = 25)

sim = sim_setting[id, 'sim']
sig.delta = sim_setting[id, 'delta'] 
# h.tmp = sim_setting[id, 'h'] 
# h = c(as.numeric(gsub(".*\\((.*)\\,.*", "\\1", h.tmp)), as.numeric(gsub(".*\\,(.*)\\;.*", "\\1", h.tmp)), as.numeric(gsub(".*\\;(.*)\\).*", "\\1", h.tmp)))

r = sim_setting[id, 'r']
dir_out = 'path_to_save_result'

exact = FALSE             #TRUE=S1; FALSE=S2
K = 3                     #total number of source population 
p = 80                  #number of variables
diffperct = 0.1
h= rep(p*diffperct,3)   #Difference between target and source
s = p/2
n0 = 100                  #target population size
nt = c(2000, 2500, 3000)    #source population size
n.test = 1000
intercept = rep(1, K+1)
LOOP=1
 # import data
 X.pool = data.matrix(read.table('./Xpool.txt', header = F))
```

### boxplot 3 by 3

```{r Generate fastCOMMUTE DONT NEED TO DO IT AGAIN}
source('core_functions_v4_woodbury.R')

diffloop<-c(2,4)
ploop<-c(600,1000)
mselist<-matrix(0,LOOP,K+1+1+1+1)
for (k in diffloop) {
  for (j in ploop) {
 diffperct = k*0.01
 p = j
 s = p/2
 h= rep(p*diffperct,3)   #Difference between target and source
 


 # Only Target & M=0 to M=K
 mseout = matrix(0,LOOP,K+1+1+1+1)

# Simulation results  
for (loop in 1:LOOP) {
#set.seed(sim = loop)
 DATA<-data_generation(loop, p, s, K, n0, nt, nov = "large", h, sig.delta, intercept, exact, r, n.test)
 X.tar =DATA$X.tar
 X.src =DATA$X.src
 y.tar =DATA$y.tar
 y.src =DATA$y.src
 delta.TL =DATA$delta.TL
 wthreshold = DATA$wthreshold 
 beta.true = DATA$beta.true
 beta.tar = ginv(t(X.tar)%*%X.tar)%*%t(X.tar)%*%y.tar

 
 a<-beta_fastCOMMUTE_generation(K, method = "fastcommute",nov = "large",X.tar,X.src,y.tar,y.src,delta.TL,wthreshold,beta.true)
   
 


# Only Target
 mseout[loop,1] =mse.fun(beta.true, beta.tar)
# M=0 
 mseout[loop,2] = mse.fun(beta.true, a[[K+1]])
# M=1 to M=K 
 for(i in 1:K){
 mseout[loop,i+2] = mse.fun(beta.true, a[[i]])
    
 }
 # lable p and diff
 mseout[loop,6] = p
 mseout[loop,7] = diffperct

}
  
  mselist<-rbind(mselist,mseout)
  
  }
} 
 
# save(mselist,file = "boxplot121.RData") 
```


### I have saved the data

```{r}
load("C:/2024Spring/fastCOMMUTE_2024/COMMUTELOOP129.RData")
load("C:/2024Spring/fastCOMMUTE_2024/boxplot121.RData")


```

### Give it a first try

```{r}
mselist2<-mselist[-c(1:LOOP),]
mselist2<-as.data.frame(mselist2)
colnames(mselist2)<-c("Target-Only",c(0:K),"p","diff")
mseout_plt <- mselist2
mseout_df = 
  pivot_longer(
    mseout_plt, 
    1:(K+2),
    names_to = "Data", 
    values_to = "MSE")
mseout_df
```

### Add COMMUTE

```{r}
mselistCOMMUTE2<-mselistCOMMUTE[-c(1:(7*LOOP)),]
mselistCOMMUTE2<-as.data.frame(mselistCOMMUTE2)
mseCOMMUTE_df <- mselistCOMMUTE2 |>
  rename( Data= methods,
         diff = diffperct,
         MSE = mseout)|>
  mutate(diff = as.numeric(diff),
         MSE = as.numeric(MSE),
         p = as.numeric(p))|>
  select(p,diff,Data,MSE)

```

### Replace Target Only

```{r}
mselasso <- as.data.frame(mselistLASSOTargetOnly[-c(1:LOOP),])
mselasso_df <- mselasso |>
  rename( Data= method,
         diff = diffperct,
         MSE = mseout)|>
  mutate(diff = as.numeric(diff),
         MSE = as.numeric(MSE),
         p = as.numeric(p))|>
  select(p,diff,Data,MSE)
mselasso_df$Data[mselasso_df$Data=="LASSOTargetOnly"]="Target-Only"
mseout_df <- mseout_df |>
  filter(Data != "Target-Only")

mseout_df<-rbind(mseout_df,mselasso_df)

```

### Combine fastCOMMUTE and COMMUTE

```{r}

mseout_df_combined<-rbind(mseCOMMUTE_df,mseout_df)

```

### Add groups

```{r}
mseout_df_combined$group <- "fastCOMMUTE"
mseout_df_combined$group[mseout_df_combined$Data =="Target-Only"] <-"Target"
mseout_df_combined$group[mseout_df_combined$Data =="w1"] <-"Source"
mseout_df_combined$group[mseout_df_combined$Data =="w2"] <-"Source"
mseout_df_combined$group[mseout_df_combined$Data =="w3"] <-"Source"
mseout_df_combined$group[mseout_df_combined$Data =="beta.syn.M0.agg.new"] <-"COMMUTE"
mseout_df_combined$group[mseout_df_combined$Data =="beta.syn.M1.agg.new"] <-"COMMUTE"
mseout_df_combined$group[mseout_df_combined$Data =="beta.syn.M2.agg.new"] <-"COMMUTE"
mseout_df_combined$group[mseout_df_combined$Data =="beta.syn.M3.agg.new"] <-"COMMUTE"


```

### Change beta.syn123.M0 to M0

```{r}
# COMMUTE
mseout_df_combined$Data[mseout_df_combined$Data =="beta.syn.M0.agg.new"] <-"M=0"
mseout_df_combined$Data[mseout_df_combined$Data =="beta.syn.M1.agg.new"] <-"M=1"
mseout_df_combined$Data[mseout_df_combined$Data =="beta.syn.M2.agg.new"] <-"M=2"
mseout_df_combined$Data[mseout_df_combined$Data =="beta.syn.M3.agg.new"] <-"M=3"

# fastCOMMUTE
mseout_df_combined$Data[mseout_df_combined$Data =="0"] <-"M=0"
mseout_df_combined$Data[mseout_df_combined$Data =="1"] <-"M=1"
mseout_df_combined$Data[mseout_df_combined$Data =="2"] <-"M=2"
mseout_df_combined$Data[mseout_df_combined$Data =="3"] <-"M=3"

```



### Making Plots

```{r}
library(tidyverse)
library(dplyr)
library(ggplotify)
library(patchwork)
library(viridis)
library(reshape2)
library(ggplot2)
library(RColorBrewer)

mseout_df_arranged<-mseout_df_combined |>
  arrange(p,diff)

# re-order x-axis
mseout_df_arranged$group = factor(mseout_df_arranged$group, c('Target','Source','COMMUTE','fastCOMMUTE'))

# mseout_df_arranged <- mseout_df_arranged|>
#   filter(group != 'COMMUTE')

plot_list =list()

mytitle <- c("p = 500, h(%) = (2,2,2)","p = 500, h(%) = (4,4,4)",
             "p = 1000, h(%) = (2,2,2)","p = 1000, h(%) = (4,4,4)")

for (i in 1:4) {
  left<-(1+(i-1)*12*LOOP)
  right<-12*LOOP*i
  
  p <- mseout_df_arranged[left:right,] |>  
  ggplot(aes(x = Data, y = MSE, fill = group)) +
  geom_boxplot()+ 
  facet_grid(cols = vars(group), scales = "free", space = "free")+
  theme(legend.position = "none",
        axis.text.x=element_text(angle=15,hjust=1))+
  # add meta-data
  labs(
      title    = mytitle [i],
      x        = " ")
  # ) +
  # ylim(0,5)
  plot_list[[i]] = p
}

library(gridExtra)
p1<-(plot_list[[1]] | plot_list[[2]]) / (plot_list[[3]] | plot_list[[4]])
p1

ggsave("Crude_Boxplot.png",p1)
```








### Time Table

```{r timetable}
library(ggplotify)
library(eoffice)
f1 = 'test1_24.pptx'
f2 = 'test2_24.pptx'
f3 = 'test3_24.pptx'
f4 = 'test4_24.pptx'

topptx(plot_list[[1]], f1)
topptx(plot_list[[2]], f2)
topptx(plot_list[[3]], f3)
topptx(plot_list[[4]], f4)

```



