---
title: "targetonlyp2000"
author: "Hwei Kuang"
date: "`r Sys.Date()`"
output: html_document
---

```{r, packages loading and default set,echo = FALSE, message = FALSE, warning = FALSE}
library(glmnet)
library(lassoshooting)
library(mvtnorm)
library(pROC)
library(rmutil)
library(grplasso)
library(Matrix)
library(sim1000G)


```

```{r defaulted values}
source('fastCOMMUTE_functions.R')

id <- 1# set 1 first to try. id <- as.numeric(Sys.getenv("SLURM_ARRAY_TASK_ID"))
sim_setting <- expand.grid(sim = 1:100, delta = 0.8, h = c("(10,10;10)","(30,30;30)","(60,60;60)","(10,60;60)"), r = 25)

sim = sim_setting[id, 'sim']
sig.delta = sim_setting[id, 'delta'] 
h.tmp = sim_setting[id, 'h'] 
h = c(as.numeric(gsub(".*\\((.*)\\,.*", "\\1", h.tmp)), as.numeric(gsub(".*\\,(.*)\\;.*", "\\1", h.tmp)), as.numeric(gsub(".*\\;(.*)\\).*", "\\1", h.tmp)))
r = sim_setting[id, 'r']
dir_out = 'path_to_save_result'
h = c(2,2,2)


exact = FALSE             #TRUE=S1; FALSE=S2
K = 3                     #total number of source population 
p = 2000                  #number of variables
s = p/2
n0 = 100                  #target population size
nt = c(1000, 1500, 2000)    #source population size
n.test = 1000
intercept = rep(1, K+1) 
```




# Generating Results(only LassoTarget) 

```{r}
library(tidyr)
 LOOP=100
 X.pool = data.matrix(read.table('./Xpool.txt', header = F))
 source('core_functions_v4_woodbury.R')
 source('COMMUTE_sim_example.R')

p=2000
s = p/2
diff2000<-c(rep(10,3),rep(30,3),rep(60,3),c(10,60,60))
mselistLASSOTargetOnly<-matrix(0,LOOP,4)
for (k in 1:4) {
 hrecordnumber = k
 h= diff2000[(1+3*(k-1)):(3*k)]   #Difference between target and source


# Simulation results  
for (loop in 1:LOOP) {
#set.seed(sim = loop)
  
 COMMUTEout = tryCatch(simutaronly2000(k*LOOP+loop, p, s, K, n0, nt, h, sig.delta, intercept, exact, r, n.test,hrecordnumber), error=function(err) list(matrix(NA,1,4)))
 mselistLASSOTargetOnly<-as.data.frame(rbind(mselistLASSOTargetOnly,as.matrix(COMMUTEout)))
 
}
 
  
  
  
} 

save(mselistLASSOTargetOnly,file = " p2000targetonly.RData")
```



